title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
title: <p align="center"> Mukul Balodi </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/mukulbalodi">GitHub</a>
  
  <br>   
  Machine Learning, NLP, Big Data
  <br>
  </p>



theme: jekyll-theme-minimal
